# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				axolotl = true
				bee = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				bat = true
				frog = true
				hoglin = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				wither_skeleton = true
				salmon = true
				piglin_brute = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				minecart = true
				ender_dragon = true
				evoker = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				ravager = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				zombie = true
				ender_pearl = true
				ghast = true
				sheep = true
				player = true
				illusioner = true
				pufferfish = true
				wolf = true
				villager = true
				zombie_villager = true
				strider = true
				hopper_minecart = true
				painting = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				mauler = true
				wildfire = true
				rascal = true

